---
environment:
  env_name: ""
  img_size: 0
  stack_size: 0
  capture_video: False
  record_every: 0
  seed: 1


---
core:
  agent:
    gamma: 0.1
    update_steps: 1
    clip_grad: 0.1
  optimizer:
    lr: 0.1
    eps: 0.1

---
dqn:
  core:
    tau: 0.1
    max_timesteps: 1
  vanilla:
    eps_start: 1.0
    eps_end: 0.1
    eps_decay: 0.1
  rainbow:
    n_steps: 1
    replay_period: 1
    learn_frequency: 1
    reward_clip: 0.1
    n_atoms: 1
    v_min: 1
    v_max: 2
  buffer:
    priority_exponent: 0.1
    priority_weight: 0.1
    buffer_size: 10
    batch_size: 1

---
ppo:
  loss_clip: 0.1
  rollout_size: 1
  num_envs: 2
  num_mini_batches: 1
  entropy_coef: 0.1
  value_loss_coef: 0.1


---
intrinsic:
  curiosity:
    comparison_weight: 0.1
    importance_weight: 0.1
    scaling_factor: 1.
  empowerment:
    test: 0.1
  surprise_based:
    test2: 0.1
